### ISSUE TITLE
5.internal-document-search　Authorization failed

### ISSUE THREAD

**Issue by noyanagi** [Azure-Samples/jp-azureopenai-samples#69]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 5.internal-document-search
Windows11環境にて、「スクラッチでの開始」の手順を実施すると、次のような権限エラーが出てデプロイに失敗します。

### Any log messages given by the failure
><以前省略>
Running "prepdocs.py"
Assume azd credential
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "C:\Users\xxxxxxxxxx\Documents\OpenAI\jp-azureopenai-samples\5.internal-document-search\scripts\prepdocs.py", line 305, in <module>
    create_search_index()
  File "C:\Users\xxxxxxxxxx\Documents\OpenAI\jp-azureopenai-samples\5.internal-document-search\scripts\prepdocs.py", line 243, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxxxx\Documents\OpenAI\jp-azureopenai-samples\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxxxx\Documents\OpenAI\jp-azureopenai-samples\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxxxx\Documents\OpenAI\jp-azureopenai-samples\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 520, in get_next
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Authorization failed.
Code:
Message: Authorization failed.
<以後省略>

### Expected/desired behavior
>

### OS and Version?
> Windows 11 Pro 22H2

### Versions
>

### Mention any other details that might be useful

> このプルリクエストと同じ問題ではないかと思います。
Fix non-subscription owner scenarios by adding Search Service Contributor role #220
https://github.com/Azure-Samples/azure-search-openai-demo/pull/220
実行ユーザーにBLOB共同作成者と検索共同作成者のロールを追加する必要があるようです。
このプルリクエストのパッチを充てるとエラーなく動くようになりました。

**Comment by rukasakurai** [comment]
こちらについて報告ありがとうございます。記載いただいた情報をもとに、エラー再現を試みたいのですが再現することができなかったので、こちらのIssueはCloseさせていただきます。

再現するための条件が一致していない可能性もあるので、再び発生する際は、発生した際にお持ちだったRBAC権限やPowerShell/bashのどちらで実行したか等含めて記載いただけると再現できる可能性が高くなるかと思います。

**Comment by rukasakurai** [comment]
こちらについてご報告ありがとうございます。記載いただいた情報をもとに、エラー再現を試みたいのですが再現することができなかったので、こちらのIssueはCloseさせていただきます。

再現するための条件が一致していない可能性もあるので、再び発生する際は、発生した際にお持ちだったRBAC権限やPowerShell/bashのどちらで実行したか等含めて記載いただけると再現できる可能性が高くなるかと思います。
